module.exports=
    {
        usersTable:require('./usersTable'),
        cartTable:require('./cartTable'),
        addressTable:require('./addressTable'),
        productDetailsTable:require('./productDetailsTable'),
        bookingsTable:require('./bookingsTable'),
       authTokenTable:require('./authTokenTable'),
        productsTable:require('./productsTable'),
    };